function sectors = sectors_intraday(stocknames)
% classifes stocks from vector 'stocknames' into the 3 sectors: Financials,
% Resources and Industrials. 1 for financials, 2 for resources and 3 for
% industrials.

for j = 1:3
    for i = 1:length(stocknames)
       if j==1 && string(stocknames{i})=='DSY' | string(stocknames{i})=='FSR' | string(stocknames{i})=='INL'...
               | string(stocknames{i})=='INP' | string(stocknames{i})=='RMH' | string(stocknames{i})=='CPI'...
               | string(stocknames{i})=='SLM' | string(stocknames{i})=='NED' | string(stocknames{i})=='SBK'...
               | string(stocknames{i})=='OML'  | string(stocknames{i})=='BGA'
           combs{j}(i) = 1;  %financials
       elseif j==2 && string(stocknames{i})=='AGL' | string(stocknames{i})=='AMS' | string(stocknames{i})=='ARI'...
               |string(stocknames{i})=='ANG' | string(stocknames{i})=='BIL' | string(stocknames{i})=='GFI'...
               | string(stocknames{i})=='IMP' | string(stocknames{i})=='MND'...
               | string(stocknames{i})=='MNP' | string(stocknames{i})=='SOL' | string(stocknames{i})=='EXX'
           combs{j}(i) = 1; %Resources
       elseif j==3 && string(stocknames{i})=='APN' | string(stocknames{i})=='BVT' | string(stocknames{i})=='BTI'...
               |string(stocknames{i})=='CFR' | string(stocknames{i})=='GRT'...
               | string(stocknames{i})=='IPL' | string(stocknames{i})=='FFB' | string(stocknames{i})=='RDF'...
               | string(stocknames{i})=='MTN' | string(stocknames{i})=='REM' | string(stocknames{i})=='SAB'...
               | string(stocknames{i})=='SHP' | string(stocknames{i})=='SNH' | string(stocknames{i})=='TBS'...
               | string(stocknames{i})=='VOD' | string(stocknames{i})=='WHL' | string(stocknames{i})=='MRP'...
               | string(stocknames{i})=='BAT' | string(stocknames{i})=='NTC' | string(stocknames{i})=='NPN'...
               | string(stocknames{i})=='MEI' | string(stocknames{i})=='GRT' | string(stocknames{i})=='ITU' ...
               | string(stocknames{i})=='FFA' | string(stocknames{i})=='CCO'
           combs{j}(i) = 1; %Industrials
       else 
           combs{j}(i) = 0;
       end
    end
end

sectors = combs;
end